### ISSUE TITLE
numba.jit doesn't work with aspectize

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#19]
```
test = use(use.Path("../tests/.test1.py"), aspectize={(use.aspect.FUNCTION, ".*"):numba.jit})
```
with .test1.py:

```
def foo(x):
   return x*2
```
fails with:

```
<.test1>:1: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function foo failed at nopython mode lowering due to: can't compile foo: import of module .test1 failed
  def foo(x):

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/numba/core/environment.py in from_fndesc(cls, fndesc)
     20             # Avoid creating new Env
---> 21             return cls._memo[fndesc.env_name]
     22         except KeyError:

/usr/lib/python3.9/weakref.py in __getitem__(self, key)
    133             self._commit_removals()
--> 134         o = self.data[key]()
    135         if o is None:

KeyError: '_ZN08NumbaEnv05test17foo$241E8pyobject'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/numba/core/funcdesc.py in lookup_module(self)
     92             try:
---> 93                 return sys.modules[self.modname]
     94             except:

KeyError: '.test1'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-17-b1fb48be0463> in <module>
----> 1 test.foo(4)

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    437                     e.patch_message('\n'.join((str(e).rstrip(), help_msg)))
    438             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 439             raise e
    440         finally:
    441             self._types_active_call = []

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    370         return_val = None
    371         try:
--> 372             return_val = self.compile(tuple(argtypes))
    373         except errors.ForceLiteralArg as e:
    374             # Received request for compiler re-entry with the list of arguments

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in compile(self, sig)
    907                 with ev.trigger_event("numba:compile", data=ev_details):
    908                     try:
--> 909                         cres = self._compiler.compile(args, return_type)
    910                     except errors.ForceLiteralArg as e:
    911                         def folded(args, kws):

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in compile(self, args, return_type)
     77 
     78     def compile(self, args, return_type):
---> 79         status, retval = self._compile_cached(args, return_type)
     80         if status:
     81             return retval

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_cached(self, args, return_type)
     91 
     92         try:
---> 93             retval = self._compile_core(args, return_type)
     94         except errors.TypingError as e:
     95             self._failed_cache[key] = e

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_core(self, args, return_type)
    104 
    105         impl = self._get_implementation(args, {})
--> 106         cres = compiler.compile_extra(self.targetdescr.typing_context,
    107                                       self.targetdescr.target_context,
    108                                       impl,

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    604     pipeline = pipeline_class(typingctx, targetctx, library,
    605                               args, return_type, flags, locals)
--> 606     return pipeline.compile_extra(func)
    607 
    608 

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in compile_extra(self, func)
    351         self.state.lifted = ()
    352         self.state.lifted_from = None
--> 353         return self._compile_bytecode()
    354 
    355     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in _compile_bytecode(self)
    413         """
    414         assert self.state.func_ir is None
--> 415         return self._compile_core()
    416 
    417     def _compile_ir(self):

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in _compile_core(self)
    393                 self.state.status.fail_reason = e
    394                 if is_final_pipeline:
--> 395                     raise e
    396         else:
    397             raise CompilerError("All available pipelines exhausted")

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in _compile_core(self)
    384             res = None
    385             try:
--> 386                 pm.run(self.state)
    387                 if self.state.cr is not None:
    388                     break

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in run(self, state)
    337                     (self.pipeline_name, pass_desc)
    338                 patched_exception = self._patch_error(msg, e)
--> 339                 raise patched_exception
    340 
    341     def dependency_analysis(self):

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in run(self, state)
    328                 pass_inst = _pass_registry.get(pss).pass_inst
    329                 if isinstance(pass_inst, CompilerPass):
--> 330                     self._runPass(idx, pass_inst, state)
    331                 else:
    332                     raise BaseException("Legacy pass in use")

~/.local/lib/python3.9/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37 

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in _runPass(self, index, pss, internal_state)
    287             mutated |= check(pss.run_initialization, internal_state)
    288         with SimpleTimer() as pass_time:
--> 289             mutated |= check(pss.run_pass, internal_state)
    290         with SimpleTimer() as finalize_time:
    291             mutated |= check(pss.run_finalizer, internal_state)

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in check(func, compiler_state)
    260 
    261         def check(func, compiler_state):
--> 262             mangled = func(compiler_state)
    263             if mangled not in (True, False):
    264                 msg = ("CompilerPass implementations should return True/False. "

~/.local/lib/python3.9/site-packages/numba/core/object_mode_passes.py in run_pass(self, state)
    118                                            state.flags)
    119 
--> 120         lowered = backend_object_mode()
    121         signature = typing.signature(state.return_type, *state.args)
    122         from numba.core.compiler import compile_result

~/.local/lib/python3.9/site-packages/numba/core/object_mode_passes.py in backend_object_mode()
    113                               (state.nargs - len(state.args)))
    114 
--> 115             return self._py_lowering_stage(state.targetctx,
    116                                            state.library,
    117                                            state.func_ir,

~/.local/lib/python3.9/site-packages/numba/core/object_mode_passes.py in _py_lowering_stage(self, targetctx, library, interp, flags)
     75         )
     76         with targetctx.push_code_library(library):
---> 77             lower = pylowering.PyLower(targetctx, library, fndesc, interp)
     78             lower.lower()
     79             if not flags.no_cpython_wrapper:

~/.local/lib/python3.9/site-packages/numba/core/lowering.py in __init__(self, context, library, fndesc, func_ir, metadata)
     35         # Python execution environment (will be available to the compiled
     36         # function).
---> 37         self.env = Environment.from_fndesc(self.fndesc)
     38 
     39         # Internal states

~/.local/lib/python3.9/site-packages/numba/core/environment.py in from_fndesc(cls, fndesc)
     21             return cls._memo[fndesc.env_name]
     22         except KeyError:
---> 23             inst = cls(fndesc.lookup_globals())
     24             inst.env_name = fndesc.env_name
     25             cls._memo[fndesc.env_name] = inst

~/.local/lib/python3.9/site-packages/numba/core/funcdesc.py in lookup_globals(self)
     79         dynamically (i.e. exec)
     80         """
---> 81         return self.global_dict or self.lookup_module().__dict__
     82 
     83     def lookup_module(self):

~/.local/lib/python3.9/site-packages/numba/core/funcdesc.py in lookup_module(self)
     93                 return sys.modules[self.modname]
     94             except:
---> 95                 raise ModuleNotFoundError(
     96                     f"can't compile {self.qualname}: "
     97                     f"import of module {self.modname} failed")

ModuleNotFoundError: can't compile foo: import of module .test1 failed
```

**Comment by amogorkon** [comment]
Maybe we could have a use.isjitable check, similar to beartypeable?

**Comment by amogorkon** [comment]
Okay, next step:

in .test4:
```
import use, numba
mod = use(use.Path(".test8.py"))
mod.test = numba.njit(mod.test)
```
in .test8:
```
def test(x:int) -> int:
    return x ** 2
```
results in 
```
DEBUG: numba.core.byteflow: bytecode dump:
>          0	NOP(arg=None, lineno=3)
           2	LOAD_FAST(arg=0, lineno=3)
           4	LOAD_CONST(arg=1, lineno=3)
           6	BINARY_POWER(arg=None, lineno=3)
           8	RETURN_VALUE(arg=None, lineno=3)
DEBUG: numba.core.byteflow: pending: deque([State(pc_initial=0 nstack_initial=0)])
DEBUG: numba.core.byteflow: stack: []
DEBUG: numba.core.byteflow: dispatch pc=0, inst=NOP(arg=None, lineno=3)
DEBUG: numba.core.byteflow: stack []
DEBUG: numba.core.byteflow: dispatch pc=2, inst=LOAD_FAST(arg=0, lineno=3)
DEBUG: numba.core.byteflow: stack []
DEBUG: numba.core.byteflow: dispatch pc=4, inst=LOAD_CONST(arg=1, lineno=3)
DEBUG: numba.core.byteflow: stack ['$x2.0']
DEBUG: numba.core.byteflow: dispatch pc=6, inst=BINARY_POWER(arg=None, lineno=3)
DEBUG: numba.core.byteflow: stack ['$x2.0', '$const4.1']
DEBUG: numba.core.byteflow: dispatch pc=8, inst=RETURN_VALUE(arg=None, lineno=3)
DEBUG: numba.core.byteflow: stack ['$6binary_power.2']
DEBUG: numba.core.byteflow: end state. edges=[]
DEBUG: numba.core.byteflow: -------------------------Prune PHIs-------------------------
DEBUG: numba.core.byteflow: Used_phis: defaultdict(<class 'set'>, {State(pc_initial=0 nstack_initial=0): set()})
DEBUG: numba.core.byteflow: defmap: {}
DEBUG: numba.core.byteflow: phismap: defaultdict(<class 'set'>, {})
DEBUG: numba.core.byteflow: changing phismap: defaultdict(<class 'set'>, {})
DEBUG: numba.core.byteflow: keep phismap: {}
DEBUG: numba.core.byteflow: new_out: defaultdict(<class 'dict'>, {})
DEBUG: numba.core.byteflow: ----------------------DONE Prune PHIs-----------------------
DEBUG: numba.core.byteflow: block_infos State(pc_initial=0 nstack_initial=0):
AdaptBlockInfo(insts=((0, {}), (2, {'res': '$x2.0'}), (4, {'res': '$const4.1'}), (6, {'lhs': '$x2.0', 'rhs': '$const4.1', 'res': '$6binary_power.2'}), (8, {'retval': '$6binary_power.2', 'castval': '$8return_value.3'})), outgoing_phis={}, blockstack=(), active_try_block=None, outgoing_edgepushed={})
DEBUG: numba.core.interpreter: label 0:
    x = arg(0, name=x)                       ['x']
    $const4.1 = const(int, 2)                ['$const4.1']
    $6binary_power.2 = x ** $const4.1        ['$6binary_power.2', '$const4.1', 'x']
    $8return_value.3 = cast(value=$6binary_power.2) ['$6binary_power.2', '$8return_value.3']
    return $8return_value.3                  ['$8return_value.3']

DEBUG: numba.core.ssa: ==== SSA block analysis pass on 0
DEBUG: numba.core.ssa: Running <numba.core.ssa._GatherDefsHandler object at 0x0000029448D21880>
DEBUG: numba.core.ssa: on stmt: x = arg(0, name=x)
DEBUG: numba.core.ssa: on stmt: $const4.1 = const(int, 2)
DEBUG: numba.core.ssa: on stmt: $6binary_power.2 = x ** $const4.1
DEBUG: numba.core.ssa: on stmt: $8return_value.3 = cast(value=$6binary_power.2)
DEBUG: numba.core.ssa: on stmt: return $8return_value.3
DEBUG: numba.core.ssa: defs defaultdict(<class 'list'>,
            {'$6binary_power.2': [<numba.core.ir.Assign object at 0x0000029448D1AD90>],
             '$8return_value.3': [<numba.core.ir.Assign object at 0x0000029448D1AD30>],
             '$const4.1': [<numba.core.ir.Assign object at 0x0000029448D21820>],
             'x': [<numba.core.ir.Assign object at 0x0000029448D212B0>]})
DEBUG: numba.core.ssa: SSA violators set()
Traceback (most recent call last):
  File "G:\Python398\lib\site-packages\numba\core\environment.py", line 21, in from_fndesc
    return cls._memo[fndesc.env_name]
  File "G:\Python398\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: '_ZN08NumbaEnv05test88test_241B42c8tJTIeFCjyCbUFRqqOAK_2f6h0kCng1maAA_3d_3dEx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "G:\Python398\lib\site-packages\numba\core\dispatcher.py", line 487, in _compile_for_args
    raise e
  File "G:\Python398\lib\site-packages\numba\core\dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "G:\Python398\lib\site-packages\numba\core\dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "G:\Python398\lib\site-packages\numba\core\dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "G:\Python398\lib\site-packages\numba\core\dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "G:\Python398\lib\site-packages\numba\core\dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "G:\Python398\lib\site-packages\numba\core\compiler.py", line 693, in compile_extra
    return pipeline.compile_extra(func)
  File "G:\Python398\lib\site-packages\numba\core\compiler.py", line 429, in compile_extra
    return self._compile_bytecode()
  File "G:\Python398\lib\site-packages\numba\core\compiler.py", line 497, in _compile_bytecode
    return self._compile_core()
  File "G:\Python398\lib\site-packages\numba\core\compiler.py", line 476, in _compile_core
    raise e
  File "G:\Python398\lib\site-packages\numba\core\compiler.py", line 463, in _compile_core
    pm.run(self.state)
  File "G:\Python398\lib\site-packages\numba\core\compiler_machinery.py", line 353, in run
    raise patched_exception
  File "G:\Python398\lib\site-packages\numba\core\compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "G:\Python398\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "G:\Python398\lib\site-packages\numba\core\compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "G:\Python398\lib\site-packages\numba\core\compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "G:\Python398\lib\site-packages\numba\core\typed_passes.py", line 392, in run_pass
    lower = lowering.Lower(targetctx, library, fndesc, interp,
  File "G:\Python398\lib\site-packages\numba\core\lowering.py", line 45, in __init__
    self.env = Environment.from_fndesc(self.fndesc)
  File "G:\Python398\lib\site-packages\numba\core\environment.py", line 23, in from_fndesc
    inst = cls(fndesc.lookup_globals())
  File "G:\Python398\lib\site-packages\numba\core\funcdesc.py", line 84, in lookup_globals
    return self.global_dict or self.lookup_module().__dict__
  File "G:\Python398\lib\site-packages\numba\core\funcdesc.py", line 97, in lookup_module
    return importlib.import_module(self.modname)
  File "G:\Python398\lib\importlib\__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: Failed in nopython mode pipeline (step: native lowering)
the 'package' argument is required to perform a relative import for '.test8'
```
