### ISSUE TITLE
use(thing) - pip uninstall thing - use(thing) - crash!

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#384]
in ubuntu jupyter:

first
`python -m pip install icrecream`
`ic = use("icecream")`
then
`python -m pip uninstall icecream`
`ice = use("icecream")
goes boom:

```
Last executed at 2021-11-22 18:54:45 in 237ms

case = (False, False, True, False)
Internal Python error in the inspect module.
Below is the traceback from this internal error.


Unfortunately, your original traceback can not be constructed.

Traceback (most recent call last):
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-c2535da89264>", line 1, in <module>
    ic = use("icecream")
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/use/use.py", line 280, in wrapper
    return dispatcher.dispatch(args[1].__class__)(*args, **kw)
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/use/use.py", line 1906, in _use_str
    result = case_func(**locals())
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/typeguard/__init__.py", line 1015, in wrapper
    retval = func(*args, **kwargs)
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/use/use.py", line 634, in _import_public_no_install
    spec.loader.exec_module(mod)  # ! => cache
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/thorsten/anaconda3/lib/python3.8/site-packages/icecream/__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/home/thorsten/anaconda3/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/home/thorsten/anaconda3/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/home/thorsten/anaconda3/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/home/thorsten/anaconda3/lib/python3.8/inspect.py", line 751, in getmodule
    f = getabsfile(module)
  File "/home/thorsten/anaconda3/lib/python3.8/inspect.py", line 720, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/home/thorsten/anaconda3/lib/python3.8/inspect.py", line 696, in getsourcefile
    filename = getfile(object)
  File "/home/thorsten/anaconda3/lib/python3.8/inspect.py", line 659, in getfile
    raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'icecream' (namespace)> is a built-in module

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
    [... skipping hidden 1 frame]

<ipython-input-11-c2535da89264> in <module>
----> 1 ic = use("icecream")

~/anaconda3/lib/python3.8/site-packages/use/use.py in wrapper(*args, **kw)
    279     def wrapper(*args, **kw):
--> 280         return dispatcher.dispatch(args[1].__class__)(*args, **kw)
    281 

~/anaconda3/lib/python3.8/site-packages/use/use.py in _use_str(self, name, version, hash_algo, hashes, default, aspectize, modes)
   1905         }[case]
-> 1906         result = case_func(**locals())
   1907         log.info("result = %s", result)

~/anaconda3/lib/python3.8/site-packages/typeguard/__init__.py in wrapper(*args, **kwargs)
   1014         check_argument_types(memo)
-> 1015         retval = func(*args, **kwargs)
   1016         try:

~/anaconda3/lib/python3.8/site-packages/use/use.py in _import_public_no_install(name, spec, aspectize, fatal_exceptions, **kwargs)
    633         sys.modules[spec.name] = mod
--> 634         spec.loader.exec_module(mod)  # ! => cache
    635         if aspectize:

~/anaconda3/lib/python3.8/importlib/_bootstrap_external.py in exec_module(self, module)

~/anaconda3/lib/python3.8/importlib/_bootstrap_external.py in get_code(self, fullname)

~/anaconda3/lib/python3.8/importlib/_bootstrap_external.py in get_data(self, path)

FileNotFoundError: [Errno 2] No such file or directory: '/home/thorsten/anaconda3/lib/python3.8/site-packages/icecream/__init__.py'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2044                         # in the engines. This should return a list of strings.
-> 2045                         stb = value._render_traceback_()
   2046                     except Exception:

AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

~/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2045                         stb = value._render_traceback_()
   2046                     except Exception:
-> 2047                         stb = self.InteractiveTB.structured_traceback(etype,
   2048                                             value, tb, tb_offset=tb_offset)
   2049 

~/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1434         else:
   1435             self.tb = tb
-> 1436         return FormattedTB.structured_traceback(
   1437             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1438 

~/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1334         if mode in self.verbose_modes:
   1335             # Verbose modes need a full traceback
-> 1336             return VerboseTB.structured_traceback(
   1337                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1338             )

~/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1191         """Return a nice text document describing the traceback."""
   1192 
-> 1193         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1194                                                                tb_offset)
   1195 

~/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1149 
   1150 
-> 1151         last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
   1152 
   1153         frames = self.format_records(records, last_unique, recursion_repeat)

~/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py in find_recursion(etype, value, records)
    449     # first frame (from in to out) that looks different.
    450     if not is_recursion_error(etype, value, records):
--> 451         return len(records), 0
    452 
    453     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

**Comment by amogorkon** [comment]
Works as expected.
