### ISSUE TITLE
use.auto_install - version?!

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#394]
version 1.0???
```
>> use("numpy", modes=use.auto_install)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/sf_Dropbox/code/justuse/src/use/main.py", line 93, in call
    return self.implementation(*args, **kwargs)
  File "/media/sf_Dropbox/code/justuse/src/use/tools.py", line 42, in wrapper
    return dispatcher.dispatch(args[1].__class)(*args, **kw)
  File "/media/sf_Dropbox/code/justuse/src/use/main.py", line 720, in _use_str
    return self._use_package(
  File "/media/sf_Dropbox/code/justuse/src/use/main.py", line 789, in _use_package
    return _fail_or_default(result, default)
  File "/media/sf_Dropbox/code/justuse/src/use/pimp.py", line 923, in _fail_or_default
    raise exception
RuntimeWarning: Please specify version and hash for auto-installation of 'numpy'.
A webbrowser will open to the Snyk Advisor to check whether the package is vulnerable.
If you want to auto-install the latest version:
use("numpy", version="1.0", hashes={'34f3456f530ae8b44231c63082c8899fe9c983fd9b108c997c4b1c8c2d435333', '9864424631775b0c052f3bd98bc2712d131b3e2cd95d1c0c68b91709170890b0', '1403b4e2181fc72664737d848b60e65150f272fe5a1c1cbc16145ed43884065a', 'c74c699b122918a6c4611285cc2cad4a3aafdb135c22a16ec483340ef97d573c', '1247ef28387b7bb7f21caf2dbe4767f4f4175df44d30604d42ad9bd701ebb31f', '5d95668e727c75b3f5088ec7700e260f90ec83f488e4c0aaccb941148b2cd377', 'bc988afcea53e6156546e5b2885b7efab089570783d9d82caf1cfd323b0bb3dd', 'f5162ec777ba7138906c9c274353ece5603646c6965570d82905546579573f73', '2e4ed57f45f0aa38beca2a03b6532e70e548faf2debbeb3291cfc9b315d9be8f', 'a3deb31bc84f2b42584b8c4001c85d1934dbfb4030827110bc36bfd11509b7bf', 'e4799be6a2d7d3c33699a6f77201836ac975b2e1b98c2a07f66a38f499cb50ce', '8890b3360f345e8360133bc078d2dacc2843b6ee6059b568781b15b97acbe39f', 'fde96af889262e85aa033f8ee1d3241e32bf36228318a61f1ace579df4e8170d', '170b2a0805c6891ca78c1d96ee72e4c3ed1ae0a992c75444b6ab20ff038ba2cd', '81225e58ef5fce7f1d80399575576fc5febec79a8a2742e8ef86d7b03beef49f', 'b1e2312f5b8843a3e4e8224b2b48fe16119617b8fc0a54df8f50098721b5bed2', '92aafa03da8658609f59f18722b88f0a73a249101169e28415b4fa148caf7e41', 'c885bfc07f77e8fee3dc879152ba993732601f1f11de248d4f357f0ffea6a6d4', '615d4e328af7204c13ae3d4df7615a13ff60a49cb0d9106fde07f541207883ca', 'e89717274b41ebd568cd7943fc9418eeb49b1785b66031bc8a7f6300463c5898', 'e6c76a87633aa3fa16614b61ccedfae45b91df2767cf097aa9c933932a7ed1e0', '0b78ecfa070460104934e2caf51694ccd00f37d5e5dbe76f021b1b0b0d221823', '4c9c23158b87ed0e70d9a50c67e5c0b3f75bcf2581a8e34668d4e9d7474d76c6', 'c449eb870616a7b62e097982c622d2577b3dbc800aaf8689254ec6e0197cbf1e', '32fe5b12061f6446adcbb32cf4060a14741f9c21e15aaee59a207b6ce6423469', '9e6f5f50d1eff2f2f752b3089a118aee1ea0da63d56c44f3865681009b0af162', 'ad010846cdffe7ec27e3f933397f8a8d6c801a48634f419e3d075db27acf5880', '74b85a17528ca60cf98381a5e779fc0264b4a88b46025e6bcbe9621f46bb3e63', '69077388c5a4b997442b843dbdc3a85b420fb693ec8e33020bb24d647c164fa5', 'e3c3e990274444031482a31280bf48674441e0a5b55ddb168f3a6db3e0c38ec8'}, modes=use.auto_install)
```

**Comment by amogorkon** [comment]
looks fixed
