### ISSUE TITLE
Errors about missing packages during pip install

### ISSUE THREAD

**Issue by jabberwock** [amogorkon/justuse#44]
```bash
$ uname -a
Linux ip-[redacted] 5.8.0-1038-aws #40~20.04.1-Ubuntu SMP Thu Jun 17 13:25:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ which pip3
/home/ubuntu/.local/bin/pip3

$ pip3 --version
pip 21.1.2 from /home/ubuntu/.local/lib/python3.8/site-packages/pip (python 3.8)

$ which python3
/usr/bin/python3
$ python3 --version
Python 3.8.10

$ pip3 install justuse

Defaulting to user installation because normal site-packages is not writeable
Collecting justuse
  Downloading justuse-0.3.2.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vo8rj7tg/justuse_3873643c28504b8a8d18fd52dd7e5026/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vo8rj7tg/justuse_3873643c28504b8a8d18fd52dd7e5026/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8haaxeso
         cwd: /tmp/pip-install-vo8rj7tg/justuse_3873643c28504b8a8d18fd52dd7e5026/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vo8rj7tg/justuse_3873643c28504b8a8d18fd52dd7e5026/setup.py", line 14, in <module>
        import use
      File "/tmp/pip-install-vo8rj7tg/justuse_3873643c28504b8a8d18fd52dd7e5026/src/use/use.py", line 90, in <module>
        import mmh3
    ModuleNotFoundError: No module named 'mmh3'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/11/17/8fa79203609f9e92ae67e3133099507128c7792ae5ea87e5fb422cc7d71d/justuse-0.3.2.tar.gz#sha256=49f46a67a37a059a96fb015fef981a0226d3fb0ddeff78e9997d88032ed62016 (from https://pypi.org/simple/justuse/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading justuse-0.3.1.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vo8rj7tg/justuse_0039c71f3c7c4f9ebefe48fa7f6420c0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vo8rj7tg/justuse_0039c71f3c7c4f9ebefe48fa7f6420c0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lcjowzhk
         cwd: /tmp/pip-install-vo8rj7tg/justuse_0039c71f3c7c4f9ebefe48fa7f6420c0/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vo8rj7tg/justuse_0039c71f3c7c4f9ebefe48fa7f6420c0/setup.py", line 14, in <module>
        import use
      File "/tmp/pip-install-vo8rj7tg/justuse_0039c71f3c7c4f9ebefe48fa7f6420c0/src/use/use.py", line 85, in <module>
        import mmh3
    ModuleNotFoundError: No module named 'mmh3'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2f/0c/f6406484a8ad30b64f03f15a5ed2c97b4d3ebb84a3374a3220b428d9a3b9/justuse-0.3.1.tar.gz#sha256=743139ed7cdffc2d015ad9ce32f4765e27d90bbfcab7ed543e622493c5cb8bc8 (from https://pypi.org/simple/justuse/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading justuse-0.3.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vo8rj7tg/justuse_319ce5cf6ea54c8e8b1323bb98deb203/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vo8rj7tg/justuse_319ce5cf6ea54c8e8b1323bb98deb203/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7350g5jt
         cwd: /tmp/pip-install-vo8rj7tg/justuse_319ce5cf6ea54c8e8b1323bb98deb203/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vo8rj7tg/justuse_319ce5cf6ea54c8e8b1323bb98deb203/setup.py", line 14, in <module>
        import use
      File "/tmp/pip-install-vo8rj7tg/justuse_319ce5cf6ea54c8e8b1323bb98deb203/src/use/use.py", line 85, in <module>
        import mmh3
    ModuleNotFoundError: No module named 'mmh3'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c6/2c/a1c0c4fa17ad8d1bdab659861dcb80f8e0f461020fbefadebafd9a466d47/justuse-0.3.0.tar.gz#sha256=ad8edb9ffc4fc0ebb730001353ee1eff1bda0205223874502b6c5e2072dd873a (from https://pypi.org/simple/justuse/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading justuse-0.2.6.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vo8rj7tg/justuse_af643f4ee5164246b57f3135486f8a58/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vo8rj7tg/justuse_af643f4ee5164246b57f3135486f8a58/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xauobnqo
         cwd: /tmp/pip-install-vo8rj7tg/justuse_af643f4ee5164246b57f3135486f8a58/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vo8rj7tg/justuse_af643f4ee5164246b57f3135486f8a58/setup.py", line 14, in <module>
        import use
      File "/tmp/pip-install-vo8rj7tg/justuse_af643f4ee5164246b57f3135486f8a58/src/use/use.py", line 79, in <module>
        import mmh3
    ModuleNotFoundError: No module named 'mmh3'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4b/47/c16bd826c3753b043b0f24790256c113e2e9faeec54eedaa75c9a9c11787/justuse-0.2.6.tar.gz#sha256=5ee9423127b63fe17d36fdc03b96596a929fd62c283c0fc54f623e70626c820d (from https://pypi.org/simple/justuse/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading justuse-0.2.5.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vo8rj7tg/justuse_cccc8b6366d44894b9aa48661789bc61/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vo8rj7tg/justuse_cccc8b6366d44894b9aa48661789bc61/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kcz9z71b
         cwd: /tmp/pip-install-vo8rj7tg/justuse_cccc8b6366d44894b9aa48661789bc61/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vo8rj7tg/justuse_cccc8b6366d44894b9aa48661789bc61/setup.py", line 14, in <module>
        import use
      File "/tmp/pip-install-vo8rj7tg/justuse_cccc8b6366d44894b9aa48661789bc61/src/use/use.py", line 78, in <module>
        import mmh3
    ModuleNotFoundError: No module named 'mmh3'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e4/da/d27dacfc04c3d28392e91e53d33652d4dec2238d52dd4dd6f86d272970f1/justuse-0.2.5.tar.gz#sha256=33ca9512148554a412b32f81e31cdc8cc85eea34f75eff5b23864c95f2eead70 (from https://pypi.org/simple/justuse/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading justuse-0.2.3.post1.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vo8rj7tg/justuse_9e75ac5d40964366b3444f97fbe40359/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vo8rj7tg/justuse_9e75ac5d40964366b3444f97fbe40359/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wv00asii
         cwd: /tmp/pip-install-vo8rj7tg/justuse_9e75ac5d40964366b3444f97fbe40359/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vo8rj7tg/justuse_9e75ac5d40964366b3444f97fbe40359/setup.py", line 14, in <module>
        import use
      File "/tmp/pip-install-vo8rj7tg/justuse_9e75ac5d40964366b3444f97fbe40359/src/use/use.py", line 78, in <module>
        import anyio
    ModuleNotFoundError: No module named 'anyio'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/11/2e/3dc979067ec4fe415c2928b6cfe00ca59f7dcdb60b402ffb82ae21ccdbf3/justuse-0.2.3.post1.tar.gz#sha256=a09d4666112ce57a3855005894cbf61e4f3d15e24ab07052b7d968599d13a149 (from https://pypi.org/simple/justuse/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading justuse-0.2.3.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vo8rj7tg/justuse_a493742a6a3c433f9d3b85f5057f3dc5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vo8rj7tg/justuse_a493742a6a3c433f9d3b85f5057f3dc5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w07cw33q
         cwd: /tmp/pip-install-vo8rj7tg/justuse_a493742a6a3c433f9d3b85f5057f3dc5/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vo8rj7tg/justuse_a493742a6a3c433f9d3b85f5057f3dc5/setup.py", line 14, in <module>
        import use
      File "/tmp/pip-install-vo8rj7tg/justuse_a493742a6a3c433f9d3b85f5057f3dc5/src/use/use.py", line 78, in <module>
        import anyio
    ModuleNotFoundError: No module named 'anyio'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a3/cc/e4dc199e9e1e2275b885c2b1edf497c3992a012fa42eceb78e009122454e/justuse-0.2.3.tar.gz#sha256=f30566e8121fb2c581b8fefb38d20946170afe462ae98a131e100fdc38b8c112 (from https://pypi.org/simple/justuse/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading justuse-0.2.2.tar.gz (10.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vo8rj7tg/justuse_20e54f71fb1446cbb0f1250c6e6289f3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vo8rj7tg/justuse_20e54f71fb1446cbb0f1250c6e6289f3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z2jqkm57
         cwd: /tmp/pip-install-vo8rj7tg/justuse_20e54f71fb1446cbb0f1250c6e6289f3/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vo8rj7tg/justuse_20e54f71fb1446cbb0f1250c6e6289f3/setup.py", line 14, in <module>
        import use
      File "/tmp/pip-install-vo8rj7tg/justuse_20e54f71fb1446cbb0f1250c6e6289f3/src/use/use.py", line 78, in <module>
        import anyio
    ModuleNotFoundError: No module named 'anyio'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/07/8c/e921874af043546e5facae0974388b5ea676c6754b913b493e4e7f737bc9/justuse-0.2.2.tar.gz#sha256=1b74f2c43bb0b39d46dafb1599bc895fb87b3bee809614e8b104d80d4e429f31 (from https://pypi.org/simple/justuse/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check          cwd: /tmp/pip-install-vo8rj7tg/justuse_2865f4d7a1394852846722f62086beef/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vo8rj7tg/justuse_2865f4d7a1394852846722f62086beef/setup.py", line 12, in <module>
        import use
      File "/tmp/pip-install-vo8rj7tg/justuse_2865f4d7a1394852846722f62086beef/src/use/use.py", line 78, in <module>
        import anyio
    ModuleNotFoundError: No module named 'anyio'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/96/d9/df8955a0df7e44327ea3d26d113107e8e8759ba6b9203ffd300152b07eae/justuse-0.2.0.tar.gz#sha256=b2a8a89a487c870fb34e422baab08690cab3c866bbbb08ec6bbaf0cb2b31d8f8 (from https://pypi.org/simple/justuse/) (requires-python:>=3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading justuse-0.1.0.post5.tar.gz (7.7 kB)
Collecting anyio>=3.1.0
  Downloading anyio-3.2.1-py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 5.9 MB/s
Collecting mmh3>=2.2.0
  Downloading mmh3-3.0.0-cp38-cp38-manylinux2010_x86_64.whl (50 kB)
     |████████████████████████████████| 50 kB 9.7 MB/s
Collecting requests>=2.24.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 9.6 MB/s
Requirement already satisfied: yarl>=1.6.3 in ./.local/lib/python3.8/site-packages (from justuse) (1.6.3)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio>=3.1.0->justuse) (2.8)
Collecting sniffio>=1.1
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.24.0->justuse) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.24.0->justuse) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.24.0->justuse) (2019.11.28)
Requirement already satisfied: multidict>=4.0 in ./.local/lib/python3.8/site-packages (from yarl>=1.6.3->justuse) (5.1.0)
Building wheels for collected packages: justuse
  Building wheel for justuse (setup.py) ... done
  Created wheel for justuse: filename=justuse-0.1.0.post5-py3-none-any.whl size=7800 sha256=c9a0ea33000815077c218b0cd430b29123cf548574c73c03732c7d9209585f4f
  Stored in directory: /home/ubuntu/.cache/pip/wheels/f5/f8/8c/54a9fe67d21a3d3baf69e8a809e96e02310b52b9360a3a2304
Successfully built justuse
Installing collected packages: sniffio, requests, mmh3, anyio, justuse
Successfully installed anyio-3.2.1 justuse-0.1.0.post5 mmh3-3.0.0 requests-2.25.1 sniffio-1.2.0
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


```

**Comment by greyblue9** [comment]
Should be fixed as of a couple PR's ago (most recent batch of changes to setup.py)
