### ISSUE TITLE
case 0010 fails with "discord.py"

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#441]
```
python -m pip install discord.py
use("discord.py")
```
leads to
``` 
Traceback (most recent call last):
  File "F:\Dropbox (Privat)\code\justuse\src\.test5.py", line 3, in <module>
    mod  = use("discord.py")
  File "F:\Dropbox (Privat)\code\justuse\src\use\main.py", line 113, in __call__
    return self.__implementation(*args, **kwargs)
  File "F:\Dropbox (Privat)\code\justuse\src\use\tools.py", line 46, in wrapper
    return dispatcher.dispatch(args[1].__class__)(*args, **kwargs)
  File "F:\Dropbox (Privat)\code\justuse\src\use\main.py", line 728, in _use_str
    return self._use_package(
  File "G:\Python398\lib\site-packages\icontract\_checkers.py", line 641, in wrapper
    result = func(*args, **kwargs)
  File "F:\Dropbox (Privat)\code\justuse\src\use\main.py", line 801, in _use_package
    result = buffet_table(case, kwargs)
  File "F:\Dropbox (Privat)\code\justuse\src\use\buffet_old.py", line 40, in buffet_table
    result = case_func()
  File "F:\Dropbox (Privat)\code\justuse\src\use\buffet_old.py", line 21, in <lambda>
    (0, 0, 1, 0): lambda: pimp._import_public_no_install(**kwargs),
  File "F:\Dropbox (Privat)\code\justuse\src\use\pimp.py", line 376, in _import_public_no_install
    if mod is None:
UnboundLocalError: local variable 'mod' referenced before assignment
```

**Comment by amogorkon** [comment]
Well, afterall, failing with `use("discord.py")` actually is correct because one doesn't really *want* to import "discord.py" but "discord", so  the correct call would be `use("discord")` or more specifically `use("discord.py/discord")`, which now works.
