### ISSUE TITLE
weird _gdbm error on windows

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#485]
On vsc, windows, py 3.11.0, case (0,0,0,0), something strange about six and gdbm happens..

```
Traceback (most recent call last):
  File "F:\Dropbox (Privat)\!TetraPlex\tetraplex\prototype-server\src\tetraplex\main.py", line 1, in <module>
    import use
  File "G:\Python3.11\Lib\site-packages\use\__init__.py", line 194, in <module>
    apply_aspect(use.iter_submodules(use), beartype)
  File "G:\Python3.11\Lib\site-packages\use\aspectizing.py", line 170, in apply_aspect
    call(x)
  File "G:\Python3.11\Lib\site-packages\use\aspectizing.py", line 166, in call
    aspectize(m, decorator, module_name=module_name)
  File "G:\Python3.11\Lib\site-packages\use\aspectizing.py", line 119, in aspectize
    aspectize(obj, decorator, qualname_lst=qualname_lst, module_name=module_name)
  File "G:\Python3.11\Lib\site-packages\use\aspectizing.py", line 111, in aspectize
    obj = getattr(thing, name, None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python3.11\Lib\site-packages\six.py", line 97, in __get__
    result = self._resolve()
             ^^^^^^^^^^^^^^^
  File "G:\Python3.11\Lib\site-packages\six.py", line 120, in _resolve      
    return _import_module(self.mod)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python3.11\Lib\site-packages\six.py", line 87, in _import_module 
    __import__(name)
  File "G:\Python3.11\Lib\dbm\gnu.py", line 3, in <module>
    from _gdbm import *
ModuleNotFoundError: No module named '_gdbm'
```

**Comment by iamwavecut** [comment]
+1
