### ISSUE TITLE
dataclasses don't like use(Path())

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#8]
```
hama = use(
    Path("/media/sf_Dropbox/mcs/Code/Arrhythmia_detection/hamamea/hama.py"),
)
```

with 

```
from dataclasses import dataclass
@dataclass(init=False, repr=False)
class Stats:
    data_length: int  # total length of data
    peak_count = int  # number of detected peaks,
```
causes
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-31ead0ea4bf8> in <module>
----> 1 hama = use(
      2     Path("/media/sf_Dropbox/mcs/Code/Arrhythmia_detection/hamamea/hama.py"),
      3 )

/media/sf_Dropbox/code/use/src/use/use.py in wrapper(*args, **kw)
    135     dispatcher = singledispatch(func)
    136     def wrapper(*args, **kw):
--> 137         return dispatcher.dispatch(args[1].__class__)(*args, **kw)
    138     wrapper.register = dispatcher.register
    139     update_wrapper(wrapper, func)

/media/sf_Dropbox/code/use/src/use/use.py in _use_path(self, path, reloading, initial_globals)
    256             else:
    257                 with open(path, "rb") as file:
--> 258                     mod = build_mod(name, file.read(), initial_globals)
    259             self.__using[name] = mod, spec, inspect.getframeinfo(inspect.currentframe())
    260             return mod

/media/sf_Dropbox/code/use/src/use/use.py in build_mod(name, code, initial_globals)
    143     mod = ModuleType(name)
    144     mod.__dict__.update(initial_globals or {})
--> 145     exec(compile(code, name, "exec"), mod.__dict__)
    146     return mod
    147 

hama in <module>

~/anaconda3/lib/python3.8/dataclasses.py in wrap(cls)
   1009 
   1010     def wrap(cls):
-> 1011         return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
   1012 
   1013     # See if we're being called as @dataclass or @dataclass().

~/anaconda3/lib/python3.8/dataclasses.py in _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
    859     # things, and set the default values (as class attributes) where
    860     # we can.
--> 861     cls_fields = [_get_field(cls, name, type)
    862                   for name, type in cls_annotations.items()]
    863     for f in cls_fields:

~/anaconda3/lib/python3.8/dataclasses.py in <listcomp>(.0)
    859     # things, and set the default values (as class attributes) where
    860     # we can.
--> 861     cls_fields = [_get_field(cls, name, type)
    862                   for name, type in cls_annotations.items()]
    863     for f in cls_fields:

~/anaconda3/lib/python3.8/dataclasses.py in _get_field(cls, a_name, a_type)
    710         if (_is_classvar(a_type, typing)
    711             or (isinstance(f.type, str)
--> 712                 and _is_type(f.type, cls, typing, typing.ClassVar,
    713                              _is_classvar))):
    714             f._field_type = _FIELD_CLASSVAR

~/anaconda3/lib/python3.8/dataclasses.py in _is_type(annotation, cls, a_module, a_type, is_type_predicate)
    656             # No module name, assume the class's module did
    657             # "from dataclasses import InitVar".
--> 658             ns = sys.modules.get(cls.__module__).__dict__
    659         else:
    660             # Look up module_name in the class's module.

AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by amogorkon** [comment]
Looks like fixing relative imports also fixed this issue..

**Comment by amogorkon** [comment]
Got it again.
Thought it only applies to jupyter, but it also appears in the latest version, ubuntu VM.

```
FROM /media/sf_Dropbox/code/justuse/tests/.tests/tests_subdir/modC.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 164, in wrapper
    return dispatcher.dispatch(args[1].__class__)(*args, **kw)
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 755, in _use_path
    return fail_or_default(default, ImportError, exc)
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 203, in fail_or_default
    raise exception(msg)
ImportError: Traceback (most recent call last):
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 744, in _use_path
    mod = build_mod(name=name,
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 192, in build_mod
    exec(compile(code, f"<{name}>", "exec"), mod.__dict__)
  File "<modA>", line 5, in <module>
    use(use.Path("modB.py"))
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 164, in wrapper
    return dispatcher.dispatch(args[1].__class__)(*args, **kw)
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 755, in _use_path
    return fail_or_default(default, ImportError, exc)
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 203, in fail_or_default
    raise exception(msg)
ImportError: Traceback (most recent call last):
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 744, in _use_path
    mod = build_mod(name=name,
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 192, in build_mod
    exec(compile(code, f"<{name}>", "exec"), mod.__dict__)
  File "<modB>", line 4, in <module>
    use(use.Path("tests_subdir/modC.py"))
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 164, in wrapper
    return dispatcher.dispatch(args[1].__class__)(*args, **kw)
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 755, in _use_path
    return fail_or_default(default, ImportError, exc)
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 203, in fail_or_default
    raise exception(msg)
ImportError: Traceback (most recent call last):
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 744, in _use_path
    mod = build_mod(name=name,
  File "/media/sf_Dropbox/code/justuse/src/use/use.py", line 192, in build_mod
    exec(compile(code, f"<{name}>", "exec"), mod.__dict__)
  File "<modC>", line 10, in <module>
    class Stats:
  File "/home/thorsten/anaconda3/lib/python3.8/dataclasses.py", line 1011, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/home/thorsten/anaconda3/lib/python3.8/dataclasses.py", line 861, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/home/thorsten/anaconda3/lib/python3.8/dataclasses.py", line 861, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/home/thorsten/anaconda3/lib/python3.8/dataclasses.py", line 712, in _get_field
    and _is_type(f.type, cls, typing, typing.ClassVar,
  File "/home/thorsten/anaconda3/lib/python3.8/dataclasses.py", line 658, in _is_type
    ns = sys.modules.get(cls.__module__).__dict__
AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by amogorkon** [comment]
Works for me.
