### ISSUE TITLE
can't use("pywt", version="1.1.1")

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#85]
In jupyter (Lubuntu VM):

```
pywt = use("pywt", version="1.1.1")

Last executed at 2021-07-20 00:06:20 in 55ms

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-8c42891afa5d> in <module>
----> 1 pywt = use("pywt", version="1.1.1")

~/anaconda3/lib/python3.8/site-packages/use/use.py in wrapper(*args, **kw)
    148     dispatcher = singledispatch(func)
    149     def wrapper(*args, **kw):
--> 150         return dispatcher.dispatch(args[1].__class__)(*args, **kw)
    151     wrapper.register = dispatcher.register
    152     update_wrapper(wrapper, func)

~/anaconda3/lib/python3.8/site-packages/use/use.py in _use_str(self, name, version, initial_globals, auto_install, hash_algo, hash_value, default, aspectize, path_to_url, import_to_use, fatal_exceptions, exchange_sys_path)
    960                     exc = traceback.format_exc()
    961                 if exc:
--> 962                     return Use._fail_or_default(default, ImportError, exc)
    963 
    964             # it seems to be installed in some way, for instance via pip

~/anaconda3/lib/python3.8/site-packages/use/use.py in _fail_or_default(default, exception, msg)
    690             return default
    691         else:
--> 692             raise exception(msg)
    693 
    694     @staticmethod

ImportError: Traceback (most recent call last):
  File "/home/thorsten/anaconda3/lib/python3.8/site-packages/use/use.py", line 952, in _use_str
    spec.loader.exec_module(mod)  # ! => cache
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by amogorkon** [comment]
Fixed.
